# Generated by Django 5.0.7 on 2024-07-24 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MamaLucyHospitalapp', '0002_appointments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointments',
            new_name='Appointment',
        ),
    ]
